export type DemoProduct = readonly [
  slug: string, nameAr: string, nameEn: string, category: string,
  price: number, stock: number, description: string, image: string,
];

export const additionalVelouraProducts: readonly DemoProduct[] = [
  ['royal-oud', 'رويال عود', 'Royal Oud', 'men-perfumes', 225000, 25, 'Refined oud, dry cedar and a touch of incense in a long-lasting eau de parfum. 100 ml.', 'veloura-oud.jpg'],
  ['cedar-reserve', 'سيدار ريزيرف', 'Cedar Reserve', 'men-perfumes', 159000, 30, 'Crisp bergamot opens into cedarwood and vetiver for a polished everyday signature. 100 ml.', 'veloura-noir.jpg'],
  ['midnight-vetiver', 'ميدنايت فيتيفر', 'Midnight Vetiver', 'men-perfumes', 178000, 22, 'Smoky vetiver, black pepper and soft leather compose an elegant evening fragrance. 100 ml.', 'veloura-noir.jpg'],
  ['rose-silk', 'روز سيلك', 'Rose Silk', 'women-perfumes', 164000, 28, 'A silk-soft bouquet of rose and peony wrapped in clean white musk. 75 ml.', 'veloura-rose.jpg'],
  ['jasmine-aura', 'جاسمين أورا', 'Jasmine Aura', 'women-perfumes', 152000, 32, 'Luminous jasmine, orange blossom and a delicate amber finish. 75 ml.', 'veloura-rose.jpg'],
  ['pearl-iris', 'بيرل آيرس', 'Pearl Iris', 'women-perfumes', 188000, 20, 'Powdery iris and violet leaf meet sandalwood in a quietly sophisticated composition. 75 ml.', 'veloura-musk.jpg'],
  ['amber-santal', 'أمبر سانتال', 'Amber Santal', 'unisex', 195000, 24, 'Creamy sandalwood, golden amber and a gentle trail of warm spices. 100 ml.', 'veloura-oud.jpg'],
  ['fig-at-dawn', 'فيغ آت دون', 'Fig at Dawn', 'unisex', 148000, 30, 'Green fig, citrus peel and soft woods capture the freshness of an early morning. 100 ml.', 'veloura-musk.jpg'],
  ['white-tea-musk', 'وايت تي مسك', 'White Tea Musk', 'unisex', 138000, 35, 'White tea, neroli and airy musk create a fresh and understated daily scent. 100 ml.', 'veloura-musk.jpg'],
  ['neroli-gold', 'نيرولي غولد', 'Neroli Gold', 'unisex', 162000, 26, 'Sunlit neroli and bitter orange settle into a soft amberwood base. 100 ml.', 'veloura-rose.jpg'],
  ['oud-signature', 'عود سيغنتشر', 'Oud Signature', 'best-sellers', 212000, 25, 'A house signature of polished oud, saffron and smooth rosewood. 100 ml.', 'veloura-oud.jpg'],
  ['velvet-amber', 'فيلفت أمبر', 'Velvet Amber', 'best-sellers', 176000, 30, 'Rich amber, vanilla and tonka bean with a velvet-soft musky finish. 100 ml.', 'veloura-oud.jpg'],
  ['rose-nocturne', 'روز نوكتورن', 'Rose Nocturne', 'best-sellers', 182000, 24, 'Dark rose petals, patchouli and incense for a memorable evening trail. 75 ml.', 'veloura-rose.jpg'],
  ['discovery-coffret', 'ديسكفري كوفريت', 'Discovery Coffret', 'gift-sets', 98000, 40, 'Six 10 ml fragrances from the house collection in an elegant discovery presentation.', 'veloura-gift.jpg'],
  ['oud-and-rose-duo', 'ثنائي العود والورد', 'Oud & Rose Duo', 'gift-sets', 265000, 18, 'Two complementary 50 ml fragrances, warm oud and luminous rose, presented as a gift duo.', 'veloura-gift.jpg'],
  ['travel-signatures', 'ترافل سيغنتشرز', 'Travel Signatures', 'gift-sets', 128000, 30, 'Three refillable 15 ml travel sprays featuring the house signature compositions.', 'veloura-gift.jpg'],
  ['lumiere-2026', 'لوميير', 'Lumière', 'new-arrivals', 186000, 28, 'Bright mandarin and white florals reveal a smooth sandalwood and musk heart. 100 ml.', 'veloura-musk.jpg'],
  ['saffron-sky', 'سافرون سكاي', 'Saffron Sky', 'new-arrivals', 208000, 20, 'Saffron, pink pepper and transparent amber in a contemporary unisex blend. 100 ml.', 'veloura-noir.jpg'],
  ['petal-atelier', 'بيتال أتيليه', 'Petal Atelier', 'new-arrivals', 168000, 26, 'Fresh petals, pear and soft cashmere woods compose a modern floral eau de parfum. 75 ml.', 'veloura-rose.jpg'],
  ['private-oud-extrait', 'برايفت عود إكستريه', 'Private Oud Extrait', 'collections', 295000, 15, 'A concentrated blend of oud, resin and smoky woods from the private collection. 50 ml.', 'veloura-oud.jpg'],
  ['atelier-musc-extrait', 'أتيليه مسك إكستريه', 'Atelier Musc Extrait', 'collections', 248000, 18, 'A concentrated musk composition with iris and fine sandalwood. 50 ml.', 'veloura-musk.jpg'],
  ['heritage-amber-extrait', 'هيريتج أمبر إكستريه', 'Heritage Amber Extrait', 'collections', 278000, 16, 'Golden amber, labdanum and vanilla in a warm, concentrated house composition. 50 ml.', 'veloura-noir.jpg'],
];

export const additionalMaisonProducts: readonly DemoProduct[] = [
  ['riviera-poplin-shirt', 'قميص ريفييرا بوبلين', 'Riviera Poplin Shirt', 'men', 118000, 30, 'A crisp cotton poplin shirt with a relaxed collar and clean tailored lines.', 'maison-shirt.jpg'],
  ['atelier-linen-shirt', 'قميص أتيليه الكتان', 'Atelier Linen Shirt', 'men', 132000, 26, 'A breathable linen shirt with an easy silhouette and subtle natural texture.', 'maison-shirt.jpg'],
  ['meridian-field-jacket', 'سترة ميريديان', 'Meridian Field Jacket', 'men', 228000, 20, 'A structured cotton jacket with practical pockets and an understated finish.', 'maison-jacket.jpg'],
  ['noir-tailored-jacket', 'سترة نوار الرسمية', 'Noir Tailored Jacket', 'men', 285000, 18, 'A sharp tailored jacket with a refined lapel and a comfortable contemporary fit.', 'maison-jacket.jpg'],
  ['weekend-knit', 'ويك إند نيت', 'Weekend Knit', 'men', 142000, 28, 'A soft fine-gauge knit with a timeless neckline and an easy everyday silhouette.', 'maison-knit.jpg'],
  ['camille-linen-blouse', 'بلوزة كاميل الكتان', 'Camille Linen Blouse', 'women', 128000, 24, 'Light linen and thoughtful detailing make this relaxed blouse an everyday essential.', 'maison-shirt.jpg'],
  ['celeste-knit-top', 'قطعة سيليست المحبوكة', 'Céleste Knit Top', 'women', 138000, 28, 'A softly textured knit top with a clean neckline and comfortable drape.', 'maison-knit.jpg'],
  ['paris-wool-coat', 'معطف باريس الصوفي', 'Paris Wool Coat', 'women', 398000, 14, 'A refined wool-blend coat with a long silhouette, generous collar and warm lining.', 'maison-coat.jpg'],
  ['sienna-tailored-blazer', 'بليزر سيينا', 'Sienna Tailored Blazer', 'women', 258000, 20, 'A softly tailored blazer with considered proportions for workdays and evenings.', 'maison-jacket.jpg'],
  ['essential-cardigan', 'كارديغان إسينشال', 'Essential Cardigan', 'women', 158000, 26, 'An understated knit layer with a soft hand feel and a versatile button-front profile.', 'maison-knit.jpg'],
  ['city-shoulder-bag', 'حقيبة سيتي للكتف', 'City Shoulder Bag', 'bags', 198000, 22, 'A structured shoulder bag with an adjustable strap and a clean everyday profile.', 'maison-bag.jpg'],
  ['atelier-top-handle', 'حقيبة أتيليه', 'Atelier Top Handle', 'bags', 265000, 18, 'A polished top-handle bag with considered details and an optional shoulder strap.', 'maison-bag.jpg'],
  ['weekend-carryall', 'حقيبة ويك إند', 'Weekend Carryall', 'bags', 238000, 20, 'A generous everyday carryall with an organized interior and comfortable handles.', 'maison-bag.jpg'],
  ['mini-evening-bag', 'حقيبة ميني المسائية', 'Mini Evening Bag', 'bags', 168000, 24, 'A compact evening bag with a clean silhouette and a detachable fine strap.', 'maison-clutch.jpg'],
  ['studio-crossbody', 'حقيبة ستوديو كروس بودي', 'Studio Crossbody', 'bags', 185000, 26, 'A compact crossbody designed for daily essentials with an adjustable shoulder strap.', 'maison-clutch.jpg'],
  ['satin-evening-pouch', 'حقيبة ساتان المسائية', 'Satin Evening Pouch', 'accessories', 112000, 30, 'A softly structured evening pouch with a satin finish and a discreet closure.', 'maison-clutch.jpg'],
  ['signature-compact-bag', 'حقيبة سيغنتشر الصغيرة', 'Signature Compact Bag', 'accessories', 148000, 24, 'A compact companion with a structured profile and thoughtful everyday details.', 'maison-bag.jpg'],
  ['lumiere-knit', 'قطعة لوميير المحبوكة', 'Lumière Knit', 'new-arrivals', 156000, 28, 'A new-season fine-knit top with a light touch and an elegantly simple silhouette.', 'maison-knit.jpg'],
  ['nouveau-linen-shirt', 'قميص نوفو الكتان', 'Nouveau Linen Shirt', 'new-arrivals', 145000, 26, 'A fresh interpretation of the linen shirt with relaxed proportions and a neat collar.', 'maison-shirt.jpg'],
  ['modern-city-jacket', 'سترة مودرن سيتي', 'Modern City Jacket', 'new-arrivals', 248000, 20, 'A versatile city jacket with clean seams and a softly structured modern profile.', 'maison-jacket.jpg'],
  ['heritage-wool-coat', 'معطف هيريتج الصوفي', 'Heritage Wool Coat', 'collections', 425000, 12, 'A signature longline wool-blend coat with refined detailing and a generous drape.', 'maison-coat.jpg'],
  ['maison-signature-tote', 'حقيبة ميزون سيغنتشر', 'Maison Signature Tote', 'collections', 295000, 18, 'A signature structured tote with ample space and an understated, polished finish.', 'maison-bag.jpg'],
];
